#! /bin/bash

fix_caps() {
    if xmodmap | grep --quiet Caps_Lock
    then
        xmodmap -e "clear Lock"
        xmodmap -e "keysym Caps_Lock = BackSpace"
        if [ $1 -gt 0 ]
        then
            fix_caps $(( $1 - 1))
        fi
    fi
}

fix_caps 10
