#! /bin/sh

# Setup blurred screenshot:
scrot /tmp/screen_locked.png
mogrify -blur 0x6 /tmp/screen_locked.png

# Lock screen:
i3lock -i /tmp/screen_locked.png  # Forks.
xkb-switch -s gb

# Wait ...
if [ "$#" -eq 1 ]
then
    sleep $1
else
    sleep 20
fi

# ... before going black:
pgrep i3lock && xset dpms force off
